### ISSUE TITLE
Correct root cause of combined correction patches in annotated files

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/Identifying-Incorrect-Labels-In-CoNLL-2003#28]
In #26, the combined corrections file `all_conll_corrections_combined.csv` was patched to correct errors when applying corrections on the corpus. We need to fix the root causes in files under `corrected_labels/human_labels_audited` and run `scripts/Label_Stats.ipynb` again to generate a new `all_conll_corrections_combined.csv` with those corrections.

**Comment by frreiss** [comment]
@BryanCutler did #36 fix all these issues, or is there still more to be done?

**Comment by BryanCutler** [comment]
From what I remember, yes it fixed all of the issues, I just forgot to close this.
