### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by GSidiropoulos** [CODAIT/Identifying-Incorrect-Labels-In-CoNLL-2003#41]
Dear authors, I am trying to reproduce the results you reported in Table 3, for the case of "Akbik et al., 2019" trained and tested on the original corpus. Unfortunately, my results are different from the ones you reported. Furthermore, the results I am getting when using the author provided tagger (model) are still different from the ones reported. Do you have any insights on this? Thank you in advance!

**Comment by xuhdev** [comment]
The training process involves some randomness, and it's totally natural to see some minor discrepancies between our results and the results you produced.

I would suggest:

- Ensure you have followed the procedure described in the paper.
- Try to train on both original and corrected corpora and see if you get similar comparative results to the paper.
